# Generated by Django 4.0.6 on 2022-09-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='created',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='modified',
        ),
    ]
