# Generated by Django 4.0.6 on 2022-09-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0002_remove_coche_created_remove_coche_modified_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coche',
            unique_together=set(),
        ),
    ]
